# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(411, 515)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(10, 100, 91, 81))
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(110, 100, 91, 81))
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(210, 100, 91, 81))
        self.three.setObjectName("three")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(10, 190, 91, 81))
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(110, 190, 91, 81))
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(210, 190, 91, 81))
        self.six.setObjectName("six")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(210, 280, 91, 81))
        self.nine.setObjectName("nine")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(10, 280, 91, 81))
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(110, 280, 91, 81))
        self.eight.setObjectName("eight")
        self.plus_minus = QtWidgets.QPushButton(self.centralwidget)
        self.plus_minus.setGeometry(QtCore.QRect(10, 370, 91, 81))
        self.plus_minus.setObjectName("plus_minus")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(110, 370, 91, 81))
        self.zero.setObjectName("zero")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(210, 370, 91, 81))
        self.clear.setObjectName("clear")
        self.result = QtWidgets.QPushButton(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(310, 10, 91, 81))
        self.result.setObjectName("result")
        self.division = QtWidgets.QPushButton(self.centralwidget)
        self.division.setGeometry(QtCore.QRect(310, 100, 91, 81))
        self.division.setObjectName("division")
        self.times = QtWidgets.QPushButton(self.centralwidget)
        self.times.setGeometry(QtCore.QRect(310, 190, 91, 81))
        self.times.setObjectName("times")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(310, 280, 91, 81))
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(310, 370, 91, 81))
        self.minus.setObjectName("minus")
        self.value = QtWidgets.QTextBrowser(self.centralwidget)
        self.value.setGeometry(QtCore.QRect(10, 10, 291, 81))
        self.value.setObjectName("value")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.one.setText(_translate("mainWindow", "1"))
        self.two.setText(_translate("mainWindow", "2"))
        self.three.setText(_translate("mainWindow", "3"))
        self.four.setText(_translate("mainWindow", "4"))
        self.five.setText(_translate("mainWindow", "5"))
        self.six.setText(_translate("mainWindow", "6"))
        self.nine.setText(_translate("mainWindow", "9"))
        self.seven.setText(_translate("mainWindow", "7"))
        self.eight.setText(_translate("mainWindow", "8"))
        self.plus_minus.setText(_translate("mainWindow", "+/-"))
        self.zero.setText(_translate("mainWindow", "0"))
        self.clear.setText(_translate("mainWindow", "C"))
        self.result.setText(_translate("mainWindow", "="))
        self.division.setText(_translate("mainWindow", "÷"))
        self.times.setText(_translate("mainWindow", "X"))
        self.plus.setText(_translate("mainWindow", "+"))
        self.minus.setText(_translate("mainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
